[package]
name = "type-alias-example"
version = "0.1.0"
authors = ["Bo0km4n <pokopenkatuya@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
